[project]
name = "cs419-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cerebras-cloud-sdk>=1.50.1",
    "fastapi>=0.119.0",
    "inngest>=0.5.9",
    "llama-index>=0.14.5",
    "pydantic>=2.12.3",
    "python-dotenv>=1.1.1",
    "qdrant-client>=1.15.1",
    "uvicorn>=0.38.0",
]
